#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
export LC_ALL=en_US.UTF-8
export DYLD_LIBRARY_PATH="$PWD/.venv/lib/python3.11/site-packages/torch/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
exec .venv/bin/"$@"
